# arat: chrmgr.NAMECOLOR_WAYPOINT : colorInfo.CHR_NAME_RGB_WAYPOINT,
# altına ekle:
			# BEGIN_OFFLINE_SHOP
			chrmgr.NAMECOLOR_OFFLINESHOP : colorInfo.CHR_NAME_RGB_OFFLINESHOP,
			# END_OF_OFFLINE_SHOP